apiVersion: v1
kind: Service
metadata:
  name: {{ include "gomono.fullname" . }}
  labels:
    {{- include "gomono.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: http
      protocol: TCP
  selector:
    {{- include "gomono.selectorLabels" . | nindent 4 }}
