replicaCount: 1
containerPort: 3000

image:
  repository: credential-service
  pullPolicy: Always
  tag: ${IMAGE_TAG:latest}

imagePullSecrets: []
nameOverride: "credential-service"
fullnameOverride: "credential-service"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

secret:
  APP_JWT_SECRET: ${APP_JWT_SECRET}
  APP_GQL_AUTH_SECRET: ${APP_GQL_AUTH_SECRET}

configmap:
  PORT: "3000"
  NAME: "credential-service"
  APP_GQL_HOST: ${APP_GQL_HOST}
  APP_GQL_AUTH_HEADER: ${APP_GQL_AUTH_HEADER}
