apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hakugo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  # - host: hakugo.host
  -  http:
      paths:
      - path: /hasura(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: hasura-service
            port:
              number: 8080
