apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
  name: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      containers:
      - image: hasura/graphql-engine:v2.9.0
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: PG_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: PG_DATABASE_URL
              optional: false
        - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: PG_DATABASE_URL
              optional: false
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: HASURA_GRAPHQL_ADMIN_SECRET
              optional: false
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          valueFrom:
            configMapKeyRef:
              name: hasura-configmap
              key: HASURA_GRAPHQL_ENABLE_CONSOLE
        - name: HASURA_GRAPHQL_DEV_MODE
          valueFrom:
            configMapKeyRef:
              name: hasura-configmap
              key: HASURA_GRAPHQL_DEV_MODE
        - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
          valueFrom:
            configMapKeyRef:
              name: hasura-configmap
              key: HASURA_GRAPHQL_ENABLED_LOG_TYPES
        - name: HOST_CREDENTIAL_SERVICE
          valueFrom:
            configMapKeyRef:
              name: hasura-configmap
              key: HOST_CREDENTIAL_SERVICE
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hasura-service
spec:
  type: NodePort
  selector:
    app: hasura
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
